export const VIRTUAL_SCROLL = {
  ITEM_HEIGHT: 120,
  CONTAINER_HEIGHT: 600,
  PADDING: 16
}

export const ANIMATIONS = {
  FADE_IN_DURATION: 500,
  SLIDE_IN_DURATION: 600
}

export const NOTIFICATIONS = {
  SUCCESS_DURATION: 3000,
  ERROR_DURATION: 5000
}
